# Generated by Django 5.1.2 on 2024-11-24 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_add_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_mark_returned', 'Can mark book as returned')]},
        ),
    ]
