# Generated by Django 5.1.2 on 2024-11-25 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_author_date_of_death'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_mark_returned', 'Can mark book as returned'), ('can_view_borrowed_books', 'Can view borrowed books')]},
        ),
    ]
